### ISSUE TITLE
[bug] Re-defined functions and classes underlined incorrectly.

### ISSUE THREAD

**Issue by pradyun** [DamnWidget/anaconda#218]
In the following snippet, there is a re-definition of `MyClass.function`. (In case that isn't obvious!)
```
class MyClass(object):
    def function(self):
        pass

    def function(self):
        pass
```
Anaconda should mark `function` in the second definition. Instead it marks `def func` (off by 4)
The same is applicable for re-defined classes (except that it is off by 6 in that case).

The marking is off by 4/6 characters as it is not compensating for the `def `/`class `. So, just adding a 4/6 to the relevant place, possibly with a comment, should be enough to fix this issue.

**Comment by DamnWidget** [comment]
Fixed in fix218 branch, available in next release v1.3.6

**Comment by pradyun** [comment]
Hello! The fix works, except that you forgot to remove a print statement in linting/sublime.py. `print(error)`. Other than that, thanks for fixing this!

And Great job with the plugin! :+1:

**Comment by DamnWidget** [comment]
Yeah, I already noticed about the print, is removed in my in-development version.

Thank you.

**Comment by pradyun** [comment]
You're welcome! :smile:
