### ISSUE TITLE
UTF-8 chars break autoformatting

### ISSUE THREAD

**Issue by karolyi** [DamnWidget/anaconda#481]
Hey,

I have the following simple test code:

```python
a = '–'
```

Note, the minus character is an UTF-8 one ([Unicode heavy minus sign](http://www.fileformat.info/info/unicode/char/2796/index.htm)). This breaks Anaconda's autoformatting. It'll say 'Autoformatting failed, buffer not changed.'

Changing that heavy minus sign to a non-utf8 one makes the problem disappear.

Just reporting in here, not so serious, but still happens.

**Comment by DamnWidget** [comment]
I can't replicate it, my configuration on this test is:

OS: Linux
ST3: 3114
Anaconda: Last
Python Interpreter: 2.7.11

Do you have any logs in the console or in your Jedi cache directory?

![anim](https://cloud.githubusercontent.com/assets/329766/15336032/7815391e-1c6c-11e6-9696-d2e0969cfc3b.gif)

**Comment by karolyi** [comment]
interesting, doing a fresh anaconda install on a blank sublime makes the problem disappear.

I'm trying to find out which plugin causes the autoformatting to fail.

reverting to my sublime with all the packages and trying to autoformat which fails, produces no errors in the console. where do I find the Jedi cache dir? I've got no `jedi` under `~/.cache`.

**Comment by DamnWidget** [comment]
Are you using Linux? If you are on OS X it will be in `~/Library/Caches/Jedi`

**Comment by karolyi** [comment]
thx! I found it. there's a traceback in there:

```
2016-05-19 12:31:42,156: INFO    : client requests: pep8
2016-05-19 12:31:42,202: ERROR   : 'ascii' codec can't encode character '\u25b2' in position 561: ordinal not in range(128)
2016-05-19 12:31:42,203: DEBUG   : ['Traceback (most recent call last):', '  File "/Users/laszlokarolyi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/commands/autoformat.py", line 40, in run', "    'vid': self.vid", '  File "/Users/laszlokarolyi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/../anaconda_server/jsonserver.py", line 54, in return_back', '    print(data)', "UnicodeEncodeError: 'ascii' codec can't encode character '\\u25b2' in position 561: ordinal not in range(128)"]
2016-05-19 12:31:42,203: INFO    : About push back to ST3: b'{"vid": 19, "uid": "0dece2bcf42940198dae7cd0ff9489c5", "error": "\'ascii\' codec can\'t encode character \'\\\\u25b2\' in position 561: ordinal not in range(128)", "success": false}\r\n'
```

**Comment by karolyi** [comment]
Oh, maybe this will help you out:

the jsonserver runs with my python3.5. I found its process, with the following parameters:

`/usr/local/Cellar/python3/3.5.1/Frameworks
/Python.framework/Versions/3.5/Resources/Python.app/Contents/MacOS/Python -B /Users/laszlokarolyi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/../anaconda_server/jsonserver.py -p webmaster-stats 56010 -e /Users/
laszlokarolyi/Work/zalando/webmaster-stats/webmaster_stats,/Users/laszlokarolyi/Work/zalando/webmaster-stats/venv/lib/python3.5/site-packages`

**Comment by DamnWidget** [comment]
I still can't replicate it using Python 3.5.1 in my Linux box, I will try to replicate it later in my OS X box.

**Comment by DamnWidget** [comment]
By the way, your system is reporting that the symbol that can not be decoded is `\u25b2` that is just ▲ character

**Comment by karolyi** [comment]
Yeah, I've got another code where there's a character like that, that's failing too.
--
László Károlyi
http://linkedin.com/in/karolyi

**Comment by DamnWidget** [comment]
I could totally reproduce it in OS  X 10.10.5 using Python 3.5.1

**Comment by karolyi** [comment]
excellent! I hate to be the messenger btw :)

**Comment by DamnWidget** [comment]
Fixed, to be released

**Comment by DamnWidget** [comment]
Hey @karolyi did I released this fix? I am totally unable to remember if I did it or not, I think I did but...

**Comment by karolyi** [comment]
@DamnWidget I'm still getting the same errors. Moreover, I can't start anaconda in debug mode this time. After starting Sublime, I get the following message appearing in an alert window:

```
<Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x10aaa7710> initial check failed because:

can not connect to /Users/laszlokarolyi/Library/Application Support/Anaconda/forum-django/anaconda.sock. tried to connect 21 times during 2 seconds

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that the Unix Domain Socket file /Users/laszlokarolyi/Library/Application Support/Anaconda/forum-django/anaconda.sock exists and that you can connect to it writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(/Users/laszlokarolyi/Library/Application Support/Anaconda/forum-django/anaconda.sock)
```

also there is no jsonserver.py process started up.

**Comment by DamnWidget** [comment]
My OS X box is locked for undefined time probably the fix is in a local branch on it's hard drive :(. You can start anaconda in debug mode with: 
```
python -B ~/Application\ Support/Sublime\ Text\ 3/Packages/Anaconda/anaconda_server/jsonserver.py -p <your_project_name> DEBUG
```

Can you giive it a try to see if the problem is still the same or if its a new one?

**Comment by karolyi** [comment]
Something's not right here, but I can't figure out what.

When I start the jsonserver process with the *exact* same parameters as I see in the process list (after I shut down the original one with a kill signal), the autoformatting works.

Only when Sublime starts the jsonserver process in the background, does the autoformatting fail.

If only I could get that already running process to log somehow ...

**Comment by DamnWidget** [comment]
There should be some log in:
`~/Library/Logs/anaconda/<your_project_name>/`

**Comment by karolyi** [comment]
got it:

2016-09-01 12:09:39,517: ERROR   : 'ascii' codec can't encode character '\u2b06' in position 109: ordinal not in range(128)
2016-09-01 12:09:39,518: DEBUG   : ['Traceback (most recent call last):', '  File "/Users/laszlokarolyi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/commands/autoformat.py", line 40, in run', "    'vid': self.vid", '  File "/Users/laszlokarolyi/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_server/jsonserver.py", line 56, in return_back', '    print(data)', "UnicodeEncodeError: 'ascii' codec can't encode character '\\u2b06' in position 109: ordinal not in range(128)"]
2016-09-01 12:09:39,518: INFO    : About push back to ST3: b'{"vid": 18, "error": "\'ascii\' codec can\'t encode character \'\\\\u2b06\' in position 109: ordinal not in range(128)", "success": false, "uid": "5b9f4c45ed574296b8d3e98c95f8bd57"}\r\n'

**Comment by DamnWidget** [comment]
@karolyi  can you try the following in your OS X?

* Open a terminal
* write: `python3 -c "print(b'Espa\xc3\xb1a'.decode('utf8'))"`
* write: `PYTHONIOENCODING="utf8" python3 -c "print(b'Espa\xc3\xb1a'.decode('utf8'))"`

Paste here your results

**Comment by karolyi** [comment]
hey,

tried it, works both ways. I don't know if this makes a difference, but in terminal:
```python
Python 3.5.2 (default, Jul 28 2016, 21:28:00) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> sys
<module 'sys' (built-in)>
>>> sys.stdin.encodin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_io.TextIOWrapper' object has no attribute 'encodin'
>>> sys.stdin.encoding
'UTF-8'
>>> sys.stdout.encoding
'UTF-8'
>>> 
```

and in ST3 console:
```python
>>> sys
<module 'sys' (built-in)>
>>> sys.stdout.encoding
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: '_LogWriter' object has no attribute 'encoding'
>>> sys.stdin.encoding
'US-ASCII'
```

it seems that ST3 starts with US-ASCII charset per default.

**Comment by DamnWidget** [comment]
Do you think you can join our gitter for a second? https://gitter.im/DamnWidget/anaconda?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by DamnWidget** [comment]
You can reinstall the package control version again @karolyi :)

**Comment by karolyi** [comment]
thx!
